#makefile

# !include <win32.mak>

GEN = gen.h 
PROGRAM = cats.exe
GCC = cl
ALL_OBJ = main.obj cat_if.obj cats.obj tiger.obj home_cat_adapter.obj cat_info_printer.obj
CFLAGS = -Wall -g

#Link the program:
$(PROGRAM): $(ALL_OBJ)
	link $(ALL_OBJ) /OUT:$(PROGRAM)

# All .o files depend on their corresponding .cpp file
%.obj: %.cpp %.h $(GEN)
	$(GCC) $(CFLAGS) -c $<

