# Sample makefile

!include <win32.mak>

GEN = gen.h
PROGRAM = rev.exe
ALL_OBJ = main.obj linked_list.obj node_if.obj
COMPILER = cl
LINKER = link

$(PROGRAM): $(ALL_OBJ)
	$(LINKER) $(ALL_OBJ) /OUT:$(PROGRAM)

main.obj: main.cpp
	$(COMPILER) -c /MD main.cpp

linked_list.obj: linked_list.cpp linked_list.h $(GEN)
	$(COMPILER) -c linked_list.cpp

node_if.obj: node_if.cpp node_if.h $(GEN)
	$(COMPILER) -c node_if.cpp
