# Sample makefile

!include <win32.mak>

GEN = gen.h
PROGRAM = app.exe
ALL_OBJ = main.obj print_util.obj


$(PROGRAM): $(ALL_OBJ)
	link $(ALL_OBJ) /OUT:$(PROGRAM)

main.obj: main.cpp $(GEN)
	cl -c main.cpp 

print_util.obj: print_util.cpp print_util.h $(GEN)
	cl -c print_util.cpp
