#makefile

# !include <win32.mak>

GEN = gen.h 
PROGRAM = a.exe
# GCC = cl
GC=g++
ALL_OBJ = main.obj utils.obj
CFLAGS = -Wall -g

#Link the program:
$(PROGRAM): $(ALL_OBJ)
	link $(ALL_OBJ) /OUT:$(PROGRAM)

# All .o files depend on their corresponding .cpp file
%.obj: %.cpp %.h $(GEN)
	$(GCC) $(CFLAGS) -c $<

