# Sample makefile

!include <win32.mak>

PROGRAM = ref.exe

$(PROGRAM): main.obj utils.obj
	link main.obj utils.obj /OUT:$(PROGRAM)

main.obj: main.cpp
	cl -c main.cpp

utils.obj: utils.cpp utils.h
	cl -c utils.cpp
