#makefile

# !include <win32.mak>

GEN = gen.h 
PROGRAM = dcript.exe
GCC = cl
ALL_OBJ = main.obj binary.obj msg_print.obj
CFLAGS = -Wall -g

#Link the program:
$(PROGRAM): $(ALL_OBJ)
	link $(ALL_OBJ) /OUT:$(PROGRAM)

# All .o files depend on their corresponding .cpp file
%.obj: %.cpp %.h $(GEN)
	$(GCC) $(CFLAGS) -c $<

