@echo off

:INIT 
set MAIN_OBJ=tdd_start
set CXX_PYTHON_CONVERT=C:\cxxtest-4.3\cxxtestgen.py

if exist %MAIN_OBJ%.exe del %MAIN_OBJ%.exe

REM autogenerate cpp file for unit test:
call %CXX_PYTHON_CONVERT% --error-print -o %MAIN_OBJ%.cpp %MAIN_OBJ%.h

REM compile resulted autogenerated cpp file to an exe-file:
call g++ -I"C:\cxxtest-4.3" -o %MAIN_OBJ%.exe %MAIN_OBJ%.cpp

if exist %MAIN_OBJ%.exe goto TARGET_EXIST
goto ERROR_NO_EXE_FILE

:TARGET_EXIST
call %MAIN_OBJ%.exe
goto END

:ERROR_NO_EXE_FILE
echo ERROR: file '%MAIN_OBJ%.exe' not exist!
goto END

:END
echo Complete.
