/************************************************************************

   Description:   English texts
   File:          txteng.h
   Language:      Borland C++ 3.0
   Original:      01.11.2000/JLM

 *************************************************************************/



#define  TX0001     "\n\rFound Serial Port COM%d in address %X"
#define  TX0002     "\nSerial port %d type is 8250 (or does not exist)"
#define  TX0003     "\nSerial Port %d type is 16450/16550"
#define  TX0004     "\nSerial Port %d type is 16550AF"
#define  TX0005     "\nSerial Port %d does not exist"
#define  TX0006     "\nNo Serial Ports Found"
#define  TX0007     "no parity"
#define  TX0008     "even parity"
#define  TX0009     "odd parity"
#define  TX0010     "\nIllegal Parity %d for Port %s\n"
#define  TX0011     "\nIllegal number of data bits %d for port %s\n\r"
#define  TX0012     "\nIllegal number of stop bits %d for port %s\n\r"
#define  TX0013     "\nIllegal Baudrate %d for Port %s\n"
#define  TX0014     "\nInitializing Port %d \n\r"
#define  TX0015     "\nSerial Port %d initialization done"
#define  TX0017     "\nSerial Port %d initialization failed"
#define  TX0018     "\nNot initializing Port %d"
#define  TX0019     "\n\rDisplay frequency set to %d\n\r"
#define  TX0020     "\n\rCOM%d Input Redirected\n\r"
#define  TX0021     "\n\rCOM%d Output Redirected\n\r"

#define  TX0023     "\n\rLast Compilation: %s, %s"
#define  TX0024     "\n\rValues will be displayed with labels\n\r"
#define  TX0025     "\n\rValues will be displayed without labels\n\r"
#define  TX0026     "\n\r>TOO LONG LINE !\n\r"
#define  TX0027     "\n\rTIMEOUT. DISPLAY STOPPED !!!\n"
#define  TX0028     "\n\rCan't read com settings for port %d\n\r"
#define  TX0029     "\n\rFATAL ERRORS   :  %d"
#define  TX0030     "\n\rSEVERE ERRORS  :  %d"
#define  TX0031     "\n\rNORMAL ERRORS  :  %d"
#define  TX0032     "\n\rWARNINGS       :  %d"
#define  TX0033     "\n\rINFORMATION    :  %d"
#define  TX0034     "\n\rCode:%d Par1:%ld Par2:%ld Time:%ld Cnt:%d"
#define  TX0035     "\n\rCode:%d Time:%ld Cnt:%d"
#define  TX0036     "\n\rREMOVED ERRORS :  %d"
#define  TX0037     "\n\rShortest timeslice so far: %d\n\r"
#define  TX0038     "\n\rLongest timeslice so far: %d\n\r"
#define  TX0039     "\n\rGyro Initialization Succeeded\n\r"
#define  TX0040     "\n\rGyro Initialization Failed\n\r"
#define  TX0041     "\n\rMonitor and client port changed\n\r"
#define  TX0042     "\n\rLogging started to file %s\n\r"
#define  TX0043     "\n\rLogging stopped to file %s\n\r"
#define  TX0044     "\n\rNo files left today. Remove some ! %s\n\r"
#define  TX0045     "\n\rUnable to create file %s\n\r"
#define  TX0046     "\n\rUnable to open file %s\n\r"
#define  TX0047     "\n\rStarted log play from file %s\n\r"
#define  TX0048     "\n\rCan't open file %s for reading\n\r"
#define  TX0049     "\n\rStopped log play from file %s\n\r"
#define  TX0050     "\n\rLPT1 Input Redirected\n\r"
#define  TX0051     "\n\rCan't read %s window  settings \n\r"
#define  TX0052     "\n\rBuzzer has been turned  %s \n\r"
#define  TX0053     "\n\rCan't read %s TOS  setting \n\r"

// the menu key texts are client specific (JM 05.09.2001)

#define  TX0062     "Login, Enter Password"
#define  TX0063     "Login, Enter User ID"
#define  TX0064     "LOGOUT - OK"
#define  TX0065     "Go Back - CNL"
#define  TX0066     "CANCEL JOB - OK"
#define  TX0067     "Go Back - CNL"
#define  TX0068     "Enter Container ID"
#define  TX0069     "Enter Slot"
#define  TX0070     "Login, Enter User ID"
#define  TX0071     "BYE "
#define  TX0072     "OK "
#define  TX0073     "BYE. : DISCONNECTED BY TIMEOUT.\n"
#define  TX0074     "Place container back or"
#define  TX0075     "F4 - Enter Container ID"
#define  TX0076     "PICK WITHOUT JOB"
#define  TX0077     "Enter Container ID"
#define  TX0078     "NO GPS, CHECK CONTAINER !"
#define  TX0079     "WRONG PLACE SLOT"
#define  TX0080     "Pick container back or"
#define  TX0081     "F5 - Confirm Slot"
#define  TX0082     "PLACE WITHOUT JOB"
#define  TX0083     "NO GPS, CHECK SLOT !"
#define  TX0084     "IF REPARKING, CALL DISPATCHER"
#define  TX0085     "Confirm Job Manually - OK"
#define  TX0086     "Give New Position - OK"
#define  TX0087     "Send Alarm - OK"
#define  TX0088     "Connecting To Server "
#define  TX0089     "Re-Enter Container ID"
#define  TX0090     "WRONG TIER"
#define  TX0091     "Enter more container digits"
#define  TX0092     "Unable to connect server."  
#define  TX0093     "Trying again."
#define  TX0094     "Wrong username or password"
#define  TX0095     "Press OK"
#define  TX0096     "Updating Program"  // JO021101
#define  TX0097     "Wait for Restart" // JO021101
#define  TX0098     "Can't initialize Port %d\n\r"
#define  TX0099     "Can't load Port %d settings from comports.ini !\n\r"
#define  TX0100     "It is not allow to active connection in SLAVE mode!\n"
#define  TX0101     "By define application starts as a master!\n"
 
#define  TX0125     "HELLO"
#define  TX0126     "BYE"
#define  TX0127     "DISCONNECTING..... \n"
#define  TX0128     "DISCONNECTED BY TIMEOUT..... \n"
#define  TX0129     "CONNECTING.....  \n"
#define  TX0130     "CURRENTLY CONNECTED TO GPS!! TYPE 'QUIT' FIRST\n"
#define  TX0131     "CURRENTLY CONNECTED TO MONITOR!! TYPE 'QUIT' FIRST\n"
#define  TX0130     "CURRENTLY CONNECTED TO GPS!! TYPE 'QUIT' FIRST\n"
#define  TX0132     "HIMON"
#define  TX0133     "Date and time synchronizing..... "		
#define  TX0134     " CONNECT TIMEOUT.\n REMOTE COMPUTER DOES NOT RESPOND.\n CHECK THE CONNECTION LINE!\n"		



