#makefile

# !include <win32.mak>

GEN = gen.h 
PROGRAM = fizz_buzz.exe
GCC = cl
# ALL_OBJ = main.obj utils.obj fizz_buzz.obj
ALL_OBJ = main.obj
CFLAGS = -Wall -g

#Link the program:
$(PROGRAM): $(ALL_OBJ)
	link $(ALL_OBJ) /OUT:$(PROGRAM)

# All .o files depend on their corresponding .cpp file
%.obj: %.cpp %.h $(GEN)
	$(GCC) $(CFLAGS) -c $<

