#makefile

# !include <win32.mak>

GEN = gen.h 
PROGRAM = cats.exe
GCC = cl

ALL_OBJ = main.obj Door.obj Maze.obj MazeGame.obj Room.obj Wall.obj BombedMazeGame.obj BombedWall.obj RoomWithABomb.obj

CFLAGS = -Wall -g

#Link the program:
$(PROGRAM): $(ALL_OBJ)
	link $(ALL_OBJ) /OUT:$(PROGRAM)

# All .o files depend on their corresponding .cpp file
%.obj: %.cpp %.h $(GEN)
	$(GCC) $(CFLAGS) -c $<

