#makefile

# !include <win32.mak>

GEN = gen.h 
PROGRAM = maps.exe
GCC = cl
ALL_OBJ = main.obj cube_calc.obj oven.obj map_tst.obj phone_book_map.obj
CFLAGS = -Wall -g

#Link the program:
$(PROGRAM): $(ALL_OBJ)
	link $(ALL_OBJ) /OUT:$(PROGRAM)

# All .o files depend on their corresponding .cpp file
%.obj: %.cpp %.h $(GEN)
	$(GCC) $(CFLAGS) -c $<

