@echo off

:INIT 
:: NOTE: file with actual tests is - "catch_main.cpp"
set MAIN_OBJ=catch_main

if exist %MAIN_OBJ%.exe del %MAIN_OBJ%.exe

REM autogenerate cpp file for unit test:
::call cxxtestgen.py --error-print -o %MAIN_OBJ%.cpp %MAIN_OBJ%.h

REM compile resuted autogenerated cpp file to an exe-file:
:: call cl -EHsc -I"C:\cxxtest-4.3" -o %MAIN_OBJ%.exe %MAIN_OBJ%.cpp patient.cpp

:: call cl -EHsc -I"C:\cxxtest-4.3" -o %MAIN_OBJ%.exe %MAIN_OBJ%.cpp patient.cpp
::call cl -o %MAIN_OBJ%.exe %MAIN_OBJ%.cpp 

::file "catch.hpp" has to be in directory C:\cxxtest-4.3. 
::REM! file "catch.hpp" is in local directory now!
::Also remeber to add it "C:\cxxtest-4.3" to %MAIN_OBJ%.cpp

::call cl -EHsc -I"C:\cxxtest-4.3"  -o %MAIN_OBJ%.exe %MAIN_OBJ%.cpp rabbit.cpp winner.cpp

cl -EHsc -I"C:\cxxtest-4.3"  -o %MAIN_OBJ%.exe %MAIN_OBJ%.cpp rabbit.cpp winner.cpp

::Here file "catch.hpp" has to be in local directory
::call cl -EHsc -o %MAIN_OBJ%.exe %MAIN_OBJ%.cpp rabbit.cpp winner.cpp

if exist %MAIN_OBJ%.exe goto TARGET_EXIST
goto ERROR_NO_EXE_FILE

:TARGET_EXIST
call %MAIN_OBJ%.exe -a
goto END

:ERROR_NO_EXE_FILE
echo ERROR: file '%MAIN_OBJ%.exe' not exist!
goto END

:END
echo Complete.

