#makefile

# !include <win32.mak>

GEN = gen.h 
PROGRAM = app.exe
GCC = cl
ALL_OBJ = main.obj employee.obj idcard.obj room.obj timestamp.obj department.obj
CFLAGS = -Wall -g

#Link the program:
$(PROGRAM): $(ALL_OBJ)
	link $(ALL_OBJ) /OUT:$(PROGRAM)

# All .o files depend on their corresponding .cpp file
%.obj: %.cpp %.h $(GEN)
	$(GCC) $(CFLAGS) -c $<

